[package]
name = "sgb_unlimiter"
version = "1.2.2"
edition = "2024"
authors = [
  "ParkSnoopy <ParkSnoopy@users.noreply.github.com>",
  "milacc0000 <milacc0000@users.noreply.github.com>"
]
license = "GPL-3.0-or-later"

[lints.cargo]
non_kebab_case_bins = "allow"


[profile.release]
panic = "abort"
strip = true
lto   = true


[features]
noscript = []


[dependencies]
ansi-escapes = "0.2"
nu-ansi-term = "0.50"
base116  = { version="0.1", features=["alloc"] }
ctrlc = "3.5"
eyre = "0.6"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
env_logger = "0.11"
enable-ansi-support = "0.2"
tasklist = "0.3"
ntapi    = { version="0.4", features=["user"] }
winapi   = { version="0.3", features=["processthreadsapi", "winnt", "winbase", "securitybaseapi", "errhandlingapi"] }

[build-dependencies]
eyre = "0.6"
winres = "0.1"
